    let country = "USA";
    let continent = "North America";
    var population = 32000000;
    var isIsland=true;
    const language="English";
    var halfPopulation=population/2;
    population++;
    var populationPoland=6000000;
    var averagePopulation=33000000;
    let description= country +" and its " + population + " people speak " + language;
    console.log("The population of " + country +" in " + continent + " is " + population + ".");
    console.log("Is " + country + " an island? " + isIsland);
    console.log("The languages spoken in " + country + " are " + language + ".");
    console.log("The half population of " + country  + " is " + halfPopulation + ".");
    console.log("The new population of " + country + " is " + population + ".");
    console.log("The population of Poland is " + populationPoland + ".");
    console.log( populationPoland > population);
    console.log( population < averagePopulation);
    console.log(description);